# Generated by Django 5.2.1 on 2025-05-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_editora_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
